info:
  name: springboot-mocheng

server:
    port: 8080
    contextpath: /

spring:
  profiles:
    active: dev
  application:
    name: springboot-mocheng
  http:
    encoding.charset: UTF-8
    encoding.force: true
  aop:
    proxy-target-class: true
  freemarker:  
    allow-request-override: false  
    cache: false  
    check-template-location: true  
    charset: UTF-8  
    content-type: text/html; charset=utf-8  
    expose-request-attributes: false  
    expose-session-attributes: false  
    expose-spring-macro-helpers: false  
    suffix: .ftl  
    template-loader-path: classpath:/templates

logging:
    config: classpath:config/logback.xml
#mybatis
mybatis:
    type-aliases-package: com.mocheng.demo.model
    mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
