info:
  name: springboot-mocheng

server:
    port: 8080
    contextpath: /

spring:
  profiles:
    active: dev
  application:
    name: springboot-mocheng
  http:
    encoding.charset: UTF-8
    encoding.force: true
  aop:
    proxy-target-class: true
# activemq
  activemq:
    broker-url: tcp://59.110.232.192:61616
    user: admin
    password: :admin
    in-memory: true
    pool:
        enabled: false
    packages:
        trust-all: true

#mybatis
mybatis:
    type-aliases-package: com.mocheng.demo.model
    mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    spring: 

    
