info:
  name: springboot-mocheng

server:
    port: 8080
    contextpath: /

spring:
  profiles:
    active: dev
  application:
    name: springboot-mocheng
  http:
    encoding.charset: UTF-8
    encoding.force: true
  aop:
    proxy-target-class: true
#mybatis
mybatis:
    type-aliases-package: com.mocheng.demo.model
    mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
